name = "GattinoInteractive"
uuid = "4120b9a3-2441-4f88-b64c-abd29fac8134"
authors = ["emmac <emmacboudreau@gmail.com>"]
version = "0.1.0"

[deps]
Gattino = "f0fb3ee5-f608-41f3-a42d-dac276373afc"
ToolipsSession = "2fe55384-55bc-4df3-9d59-c817d405cd05"
